# Generated by Django 3.2.5 on 2022-02-28 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=15)),
                ('p_soldOut', models.BooleanField(default=True)),
                ('p_summary_desc', models.CharField(max_length=70)),
                ('p_simple_desc', models.CharField(max_length=140)),
                ('p_detail_desc', models.CharField(max_length=300)),
                ('p_supply_price', models.IntegerField(default=0)),
                ('p_real_price', models.IntegerField(default=0)),
                ('p_discount', models.IntegerField(default=0)),
                ('p_register_date', models.DateTimeField(auto_now=True)),
                ('p_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('p_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcolor')),
                ('p_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsize')),
            ],
        ),
    ]
